version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: supersecretpassword
      DEBUG: 'True'
      DJANGO_SETTINGS_MODULE: config.settings.local
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file: .env
    entrypoint: /entrypoint/local.sh

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    restart: unless-stopped
